# SPDX-License-Identifier: GPL-3.0-or-later
# Toolchain-level packages whose VERSION can change produced code, hashed IN
# ADDITION to the linked libraries in packages/dev-libs.*.txt (those are folded
# automatically). Compiler exact versions are captured separately by probing the
# installed gcc/clang binaries (dumpfullversion) — not from here.
# Format: <family> <package>     family = el | deb
# Deliberately curated: glibc/kernel-headers (ABI floor), binutils (ld/as →
# layout, LTO), and the code GENERATORS whose version changes generated source
# (bison, flex, swig, autoconf, automake, libtool). NOT included: strace, perf,
# git, rsync, tar/gzip, texinfo — they do not affect the emitted binaries.
el  glibc
el  glibc-devel
el  kernel-headers
el  binutils
el  bison
el  flex
el  swig
el  autoconf
el  automake
el  libtool
deb libc6
deb libc6-dev
deb linux-libc-dev
deb binutils
deb bison
deb flex
deb swig
deb autoconf
deb automake
deb libtool
