# SPDX-License-Identifier: GPL-3.0-or-later
# Full versions for from-source compiler builds (COMPILER_SOURCE=source|auto).
# One row per: <kind> <major> <full-version>. Edit to pin what you need; a major
# requested for source build MUST have a row here or the build fails loud.
#   kind  major  full
gcc   13  13.3.0
gcc   14  14.2.0
gcc   15  15.2.0
llvm  18  18.1.8
llvm  19  19.1.7
llvm  20  20.1.8
llvm  21  21.1.0
